# Generated by Django 5.2.2 on 2025-08-28 16:10

import payment.apps.transactions.models
import payment.apps.transactions.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='additional_completion_document',
            field=models.FileField(blank=True, help_text='Additional completion document if needed (any file type)', null=True, upload_to=payment.apps.transactions.models.transaction_file_upload_path, validators=[payment.apps.transactions.storage.validate_supporting_document]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_barcode_image',
            field=models.FileField(blank=True, help_text="Receiver's barcode picture (any file type) - stored in GCP Cloud Storage", null=True, upload_to=payment.apps.transactions.models.transaction_file_upload_path, validators=[payment.apps.transactions.storage.validate_barcode_image]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_completion_document',
            field=models.FileField(blank=True, help_text='Transaction completion document uploaded by admin (any file type)', null=True, upload_to=payment.apps.transactions.models.transaction_file_upload_path, validators=[payment.apps.transactions.storage.validate_supporting_document]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_payment_slip',
            field=models.FileField(blank=True, help_text="User's payment slip or proof of payment (any file type)", null=True, upload_to=payment.apps.transactions.models.transaction_file_upload_path, validators=[payment.apps.transactions.storage.validate_supporting_document]),
        ),
    ]
