# Generated by Django 5.2.2 on 2025-08-14 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_transaction_created', models.BooleanField(default=True, help_text='Email when transaction is created')),
                ('email_transaction_updated', models.BooleanField(default=True, help_text='Email when transaction is updated')),
                ('email_transaction_completed', models.BooleanField(default=True, help_text='Email when transaction is completed')),
                ('push_transaction_created', models.BooleanField(default=True, help_text='Push notification when transaction is created')),
                ('push_transaction_updated', models.BooleanField(default=True, help_text='Push notification when transaction is updated')),
                ('push_transaction_completed', models.BooleanField(default=True, help_text='Push notification when transaction is completed')),
                ('admin_new_transactions', models.BooleanField(default=True, help_text='Notify admin of new transactions (admin only)')),
                ('user', models.OneToOneField(help_text='User preferences', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_token', models.TextField(help_text='FCM device registration token', unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], help_text='Type of device', max_length=10)),
                ('device_name', models.CharField(blank=True, help_text='Device name or identifier', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether device is active for notifications')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Last time device was used')),
                ('user', models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_devices',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='fcm_devices_user_id_a9778f_idx'), models.Index(fields=['device_type'], name='fcm_devices_device__98e505_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('transaction_created', 'Transaction Created'), ('transaction_updated', 'Transaction Updated'), ('transaction_processing', 'Transaction Processing'), ('transaction_completed', 'Transaction Completed'), ('transaction_failed', 'Transaction Failed'), ('transaction_cancelled', 'Transaction Cancelled')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('transaction_id', models.IntegerField(blank=True, help_text='Related transaction ID', null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Related transaction reference number', max_length=50, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', help_text='Notification delivery status', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When notification was delivered', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read by user', null=True)),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_218e2a_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx'), models.Index(fields=['transaction_id'], name='notificatio_transac_fec598_idx'), models.Index(fields=['transaction_reference'], name='notificatio_transac_62de0a_idx')],
            },
        ),
    ]
