# Generated by Django 5.2.2 on 2025-08-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Related transaction ID (string-based primary key)', max_length=26, null=True),
        ),
    ]
